# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-11 04:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trainManage', '0002_auto_20161211_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='\u8ba2\u5355\u7f16\u53f7')),
                ('user_name', models.CharField(max_length=20, verbose_name='\u7528\u6237\u540d')),
                ('passenger_name', models.CharField(max_length=20, verbose_name='\u4e58\u5ba2\u59d3\u540d')),
                ('passenger_id', models.CharField(max_length=20, verbose_name='\u4e58\u5ba2\u8eab\u4efd\u8bc1\u53f7')),
                ('passenger_phone', models.CharField(max_length=10, verbose_name='\u7535\u8bdd')),
                ('student', models.IntegerField(default=0, verbose_name='\u5b66\u751f\u7968')),
                ('order_time', models.TimeField(verbose_name='\u8ba2\u7968\u65f6\u95f4')),
                ('trip_date', models.TimeField(verbose_name='\u51fa\u53d1\u65e5\u671f')),
                ('pay', models.FloatField(default=0, verbose_name='\u91d1\u989d')),
                ('end_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_station', to='trainManage.Station')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainManage.Seat')),
                ('start_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_station', to='trainManage.Station')),
                ('train_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainManage.Train')),
            ],
        ),
    ]
