# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-11 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketQuery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(default=0, verbose_name='\u8ba2\u5355\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.DateTimeField(verbose_name='\u8ba2\u7968\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='order',
            name='trip_date',
            field=models.DateTimeField(verbose_name='\u51fa\u53d1\u65e5\u671f'),
        ),
    ]
