# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-01 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainManage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='arrive_time',
            field=models.CharField(max_length=10, verbose_name='\u5230\u7ad9\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='run',
            name='distance_count',
            field=models.FloatField(verbose_name='\u91cc\u7a0b\u6570'),
        ),
        migrations.AlterField(
            model_name='run',
            name='order_of_station',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='station',
            name='station_city',
            field=models.CharField(max_length=20, verbose_name='\u6240\u5c5e\u57ce\u5e02'),
        ),
        migrations.AlterField(
            model_name='station',
            name='station_name',
            field=models.CharField(max_length=20, verbose_name='\u9014\u7ecf\u8f66\u7ad9'),
        ),
        migrations.AlterField(
            model_name='train',
            name='distance',
            field=models.FloatField(verbose_name='\u603b\u91cc\u7a0b\u6570'),
        ),
        migrations.AlterField(
            model_name='train',
            name='num_station',
            field=models.IntegerField(default=-1, verbose_name='\u603b\u7ad9\u70b9\u6570'),
        ),
        migrations.AlterField(
            model_name='train',
            name='train_id',
            field=models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='\u5217\u8f66\u7f16\u53f7'),
        ),
        migrations.AlterField(
            model_name='train',
            name='train_type',
            field=models.CharField(max_length=1, verbose_name='\u5217\u8f66\u7c7b\u578b'),
        ),
    ]
