# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-06 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainManage', '0002_auto_20161101_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='distance',
            field=models.FloatField(default=0, verbose_name='\u603b\u91cc\u7a0b\u6570'),
        ),
        migrations.AlterField(
            model_name='train',
            name='num_station',
            field=models.IntegerField(default=0, verbose_name='\u603b\u7ad9\u70b9\u6570'),
        ),
        migrations.AlterField(
            model_name='train',
            name='train_type',
            field=models.CharField(default='K', max_length=1, verbose_name='\u5217\u8f66\u7c7b\u578b'),
        ),
    ]
