# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-10 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainManage', '0004_auto_20161108_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='carriage_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='seat',
            name='seat_id',
            field=models.IntegerField(),
        ),
    ]
