# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-25 03:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('run_key', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('order_of_station', models.IntegerField(default=-1)),
                ('arrive_time', models.CharField(max_length=10)),
                ('distance_count', models.FloatField(default=-1)),
                ('count_over_night', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('seat_key', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('carriage_id', models.IntegerField(default=-1)),
                ('seat_id', models.IntegerField(default=-1)),
                ('seat_type', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.IntegerField(default=-1)),
                ('station_name', models.CharField(max_length=20)),
                ('station_city', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('train_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('train_type', models.CharField(max_length=1)),
                ('num_station', models.IntegerField(default=-1)),
                ('distance', models.FloatField(default=-1)),
            ],
        ),
        migrations.AddField(
            model_name='seat',
            name='train_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainManage.Train'),
        ),
        migrations.AddField(
            model_name='run',
            name='station_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainManage.Station'),
        ),
        migrations.AddField(
            model_name='run',
            name='train_come_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainManage.Train'),
        ),
    ]
