# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-12 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainManage', '0001_initial1'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seat',
            options={'ordering': ['seat_key', 'date']},
        ),
        migrations.AlterField(
            model_name='run',
            name='arrive_time',
            field=models.TimeField(max_length=10, verbose_name='\u5230\u7ad9\u65f6\u95f4'),
        ),
    ]
