# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-11 04:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainManage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_type', models.CharField(max_length=20, verbose_name='\u5217\u8f66\u7c7b\u578b')),
                ('seat_type', models.CharField(max_length=20, verbose_name='\u5ea7\u4f4d\u7c7b\u578b')),
                ('ratio_student', models.FloatField(default=1, verbose_name='\u5b66\u751f\u7968\u6253\u6298\u7cfb\u6570')),
                ('price_per_km', models.FloatField(default=0.5, verbose_name='\u6bcf\u516c\u91cc\u8ba1\u4ef7')),
            ],
        ),
        migrations.AlterField(
            model_name='carriage',
            name='seat_type',
            field=models.CharField(choices=[('shangwu', '\u5546\u52a1\u5ea7'), ('yideng', '\u4e00\u7b49\u5ea7'), ('erdeng', '\u4e8c\u7b49\u5ea7'), ('ruanwo', '\u8f6f\u5367'), ('yingwo', '\u786c\u5367'), ('yingzuo', '\u786c\u5ea7')], max_length=10),
        ),
    ]
