# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-11 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainManage', '0002_auto_20161211_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSpan',
            fields=[
                ('time', models.DateField(primary_key=True, serialize=False)),
            ],
        ),
    ]
