# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-11 07:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainManage', '0003_timespan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainManage.TimeSpan'),
        ),
    ]
