# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-08 09:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainManage', '0003_auto_20161106_1030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='run',
            options={'ordering': ['train_come_by', 'order_of_station']},
        ),
    ]
