# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-03 14:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('passenger_name', models.CharField(max_length=20, verbose_name='\u4e58\u8f66\u4eba\u59d3\u540d')),
                ('passenger_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='\u8eab\u4efd\u8bc1\u53f7\u7801')),
                ('student', models.IntegerField(default=0, verbose_name='\u5b66\u751f\u7968')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
